# Au

name: Auto Label VSCode Issues
on: 
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  jobs:
    # gh cli, dockerized in alpine
    runs-on: maniator/gh
    steps: 
      - run: echo "job was triggered, and sucessfully ran"
      - run: echo "Job is running on ${{runner.os}}."
      - run: echo "GITHUB_EVENT_NAME: ${{GITHUB_EVENT_NAME}}"
      - run: echo "GITHUB_REF_NAME: ${{GITHUB_REF_NAME}}"
      - run: ls ${{RUNNER_TOOL_CACHE}}

